### ISSUE TITLE
Set your venom session Venom Session and configure your Whatsapp Session:

### ISSUE THREAD

**Issue by erenergul** [felipedamacenoteodoro/laravel-whatsapp-notification-channel#4]
What do you mean for this one ? Because link doesnt work and I really dont understand where to get those sessions code ? Can you please explain ?

Thank you.

**Comment by parallels999** [comment]
The link for set venom session does not work
https://orkestral.github.io/venom/pages/Getting%20Started/creating-client.html
https://github.com/felipedamacenoteodoro/laravel-whatsapp-notification-channel/blob/f9f8e5f5673b5e169ae578d9e225c2c6287790ba/README.md?plain=1#L65-L67

**Comment by felipedamacenoteodoro** [comment]
> The link for set venom session does not work https://orkestral.github.io/venom/pages/Getting%20Started/creating-client.html
> 
> https://github.com/felipedamacenoteodoro/laravel-whatsapp-notification-channel/blob/f9f8e5f5673b5e169ae578d9e225c2c6287790ba/README.md?plain=1#L65-L67

Hello you can use the https://github.com/wppconnect-team/wppconnect

**Comment by felipedamacenoteodoro** [comment]
New release avaliable, pleasy for alternative of venon you can use the https://github.com/wppconnect-team/wppconnect 

wppconnect server
